### ISSUE TITLE
Missing GMST Settings

### ISSUE THREAD

**Issue by SomeCrazyGuy** [rfuzzo/sfgmstenable#1]
Looks like you are missing about 500 or so non-string GMST records from the game, specifically the scoped records that have a colon ':' character in them like how INI settings do. [Here is a pastebin link](https://pastebin.com/Z1sUYWSF) to the list generated by the [LiveINI](https://www.nexusmods.com/starfield/mods/976) tool. I am the author of LiveINI so maybe we could collaborate in the future.

**Comment by rfuzzo** [comment]
thanks!
